# Createing Numpy Arrays

Start by installing numpy and then importing numpy as np 

In [1]:
pip install NUMPY

     --------------------------------------- 14.7/14.7 MB 28.5 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

Once Numpy has been installed start creating arrays w/ built in functions in Numpy. 
1st use the arrange() functions to create an evenly spaced array with the following lines of code: 

In [3]:
#creates a range from 0 to 9
al = np.arange(10) 

# 0 1 2 3 4 5 6 7 8 9
print(al)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
#10
print(al.shape)

(10,)


To specigy a step in the arrange() function. 

In [6]:
#creates a range from 0 to 9, step 2
a2 = np.arange(0,10,2)
print(a2)

[0 2 4 6 8]


To create an array of a specific size filled with 0s, use the zeros() function in the following code: 

In [8]:
a3 = np.zeros(5) # create an array with all 0s
print(a3) # [ 0.  0.  0.  0.  0.]
print(a3.shape) # (5,) 


[0. 0. 0. 0. 0.]
(5,)



You can aslo create 2-d arrays useing the zeros() functions. The following line of code demostrates this: 

In [9]:
a4 = np.zeros((2,3)) # array of rank 2 with all 0s; 2 rows and 3 columns 
print(a4.shape) # (2,3)
print(a4)   


(2, 3)
[[0. 0. 0.]
 [0. 0. 0.]]


To fill an array with specific number instead of 0, use the full() function in the following lines of code:


In [10]:
a5 = np.full((2,3), 8) # array of rank 2 with all 8s
print(a5) 

[[8 8 8]
 [8 8 8]]


To create an array that mirros an identity matrix in NumPy, you can do so using the eye() function. 

In [11]:
 a6 = np.eye(4) # 4x4 identity matrix
 print(a6)     

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


To create an array filled with random numbers, you can use the random() function from numpy.random module: 

In [12]:
a7 = np.random.random((2,4))   # rank 2 array (2 rows 4 columns) with # random                values
print(a7) 

[[0.09197071 0.86184624 0.52518634 0.84351667]
 [0.48552909 0.07597848 0.62800314 0.00970685]]


Another way to creat a Numpy array is to create it from a Python list as follows: 

In [13]:
 list1 = [1,2,3,4,5] # list1 is a list in Python
 r1 = np.array(list1) # rank 1 array
 print(r1) # [1 2 3 4 5]


[1 2 3 4 5]


# Array Indexing 
The following code creates another array named r2, which is 2-d: 



In [14]:
 list2 = [6,7,8,9,0]
 r2 = np.array([[1,2,3,4,5] , [6,7,8,9,0]])
 # rank 2 array
print(r2) 
print(r2.shape) # (2,5) 
print(r2[0,0]) # 1
print(r2[0,1]) # 2
print(r2[1,0]) # 6


[[1 2 3 4 5]
 [6 7 8 9 0]]
(2, 5)
1
2
6


# Boolean Indexing 


In [15]:
print(r1>2) # [False False True True True]
print(r1[r1>2]) # [3 4 5] 


[False False  True  True  True]
[3 4 5]


Consider the following example

In [16]:
nums = np.arange(20)
print(nums) 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


If you want all the odd #'s froma the list, use Boolean indexing:

In [18]:
odd_num = nums[nums % 2 == 1]
print(odd_num) 

[ 1  3  5  7  9 11 13 15 17 19]


# Slicing Arrays 
Slicing in NumPy arrays is similar to how it works w/ a Python list
Consider the following example:

In [19]:
a = np.array([[1,2,3,4,5], [4,5,6,7,8], [9,8,7,6,5]]) # rank 2 array
print(a) 

[[1 2 3 4 5]
 [4 5 6 7 8]
 [9 8 7 6 5]]


Extract the last two rows and first two columns, use slicing: 

In [21]:
b1 = a[1:3, :3] # row 1 to 3 (not inclusive) and first 3 columns
print(b1)

[[4 5 6]
 [9 8 7]]


# Reshaping Arrays
The reshape() function is used to change the dimensions of an array. 

In [23]:
b5 = np.array([9,8,7,6,5])
''' using b5 ( which is rank 1 array)ex, you can reshape it to a rank 2 
array as follows:  '''
b5 = b5.reshape(1,-1)
print(b5)

[[9 8 7 6 5]]


In the above cell,you call the reshape() function with two arguments. The first 1 indicates that you want to convert it into rank 2 array with 1 row, and the ‐1 indicates that you will leave it to the reshape() function to create the correct number of columns. 

In more complex cases, however, it is always convenient to be able to use ‐1 to let the function decide on the number of rows or columns to create.

Here is another example of how to reshape b5 (which is a rank 2 array) to rank 1: b5.reshape(-1,) ''' [9 8 7 6 5] ''' The ‐1 indicates that you let the function decide how many rows to create as long as the end result is a rank 1 array.



To convert a rank 2 array to a rank 1 array, you can also use the flatten() or ravel() functions. The flatten() function always returns a copy of the array, while the ravel() and reshape() functions return a view (reference) of the original array.


In [24]:
r2= np.array([[1,2,3,4],[5,6,7,8]])  
r2.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

# Array Math 

In [25]:
x1 = np.array([[1,2,3],[4,5,6]])
y1 = np.array([[7,8,9],[2,3,4]])

# to add together usee '+' operator as follows:
print(x1+ y1)

[[ 8 10 12]
 [ 6  8 10]]


Array math is important, as it can be used to perform vector calculations. A good example is as follows:


In [30]:
 x = np.array([2,3])
 y = np.array([4,2])
 z = x + y'''[6,5]

SyntaxError: EOF while scanning triple-quoted string literal (1335460173.py, line 3)

You can also use the np.add() function to add two arrays: 

In [32]:
 x1 = np.array([[1,2,3],[4,5,6]])
 y1 = np.array([[7,8,9],[2,3,4]])
np.add(x1,y1)


array([[ 8, 10, 12],
       [ 6,  8, 10]])

You can also perform subtraction, multiplication, as well as division with NumPy arrays:



In [33]:
print(x1 - y1) # same as np.subtract(x1,y1) ''' [[-6 -6 -6] [ 2 2 2]] ''‘
print(x1 * y1) # same as np.multiply(x1,y1) ''' [[ 7 16 27] [ 8 15 24]] ''' 
print(x1 / y1)

[[-6 -6 -6]
 [ 2  2  2]]
[[ 7 16 27]
 [ 8 15 24]]
[[0.14285714 0.25       0.33333333]
 [2.         1.66666667 1.5       ]]


## Dot Product 
Dot Product:
given two vectors—a = [a1, a2, …, an] and b = [b1, b2, …, bn]—the dot product of these two vectors is a1b1 + a2b2 + … + anbn.
In NumPy, dot product is accomplished using the dot() function:


In [34]:
x = np.array([2,3]) 
y = np.array([4,2])
np.dot(x,y) # 2x4 + 3x2 = 14


14

Dot products also work on rank 2 arrays. If you perform a dot product of two rank 2 arrays, it is equivalent to the following matrix multiplication:


In [35]:
 x2 = np.array([[1,2,3],[4,5,6]])
 y2 = np.array([[7,8],[9,10], [11,12]]) 
print(np.dot(x2,y2)) 

[[ 58  64]
 [139 154]]


## Matrix 

a matrix is strictly two‐dimensional, while an ndarray can be multidimensional.
Creating a matrix object is similar to creating a NumPy array:


In [37]:
 x2 = np.matrix([[1,2],[4,5]])
 y2 = np.matrix([[7,8],[2,3]])
#You can also convert a NumPy array to a matrix using the asmatrix() function:
 x1 = np.array([[1,2],[4,5]])
 y1 = np.array([[7,8],[2,3]])
 x1 = np.asmatrix(x1)
 y1 = np.asmatrix(y1)


# Cont on Matrix 
Another important difference between an ndarray and a matrix occurs when you perform multiplications on them.
When multiplying two ndarray objects, the result is the element‐by‐element multiplication. On the other hand, when multiplying two matrix objects, the result is the dot product (equivalent to the np.dot() function):


In [38]:
 x1 = np.array([[1,2],[4,5]])
 y1 = np.array([[7,8],[2,3]])
 print(x1 * y1) # element-by-element multiplication ''' [[ 7 16] [ 8 15]] ''‘
 x2 = np.matrix([[1,2],[4,5]])
 y2 = np.matrix([[7,8],[2,3]])
 print(x2 * y2) # dot product; same as np.dot() 

[[ 7 16]
 [ 8 15]]
[[11 14]
 [38 47]]


## Cumulative Sum 
When dealing with When dealing with numerical data, there is a need to find the cumulative sum of numbers in a NumPy array. Consider the following array:


In [40]:
np.array([(1,2,3),(4,5,6), (7,8,9)]) 
print(a) 
'''You can call the cumsum() function to get the 
cumulative sum of the elements:
'''

[[1 2 3 4 5]
 [4 5 6 7 8]
 [9 8 7 6 5]]


'You can call the cumsum() function to get the \ncumulative sum of the elements:\n'

# Go back to slide 18 and slide 19 we started on slide 20 in class


#Numpy Sorting 
NumPy provides a number of efficient sorting functions that make it very easy to sort an array.
The first function for sorting is sort(), which takes in an array and returns a sorted array.


In [42]:
 ages = np.array([34,12,37,5,13])
 sorted_ages = np.sort(ages) # does not modify the original array
print(sorted_ages) # [ 5 12 13 34 37] 
print(ages) 

[ 5 12 13 34 37]
[34 12 37  5 13]


the sort() function does not modify the original array.
 Instead it returns a sorted array. If you want to sort the original array, call the sort() function on the array itself as follows:


In [43]:
ages.sort() # modifies the array
print(ages) # [ 5 12 13 34 37]


[ 5 12 13 34 37]


In [44]:
#There is another function used for sorting—argsort(). 
example: ages = np.array([34,12,37,5,13]) 
print(ages.argsort()) # [3 1 4 0 2] 


[0 1 2 3 4]


The argsort() function returns the indices that will sort an array. In the preceding example, the first element (3) in the result of the argsort() function means that the smallest element after the sort is in index 3 of the original array, which is the number 5. The next number is in index 1, which is the number 12, and so on.


Imagine that you have three arrays representing a list of people, along with their ages and heights: 


In [47]:
persons = np.array(['Johnny','Mary','Peter','Will','Joe'])
ages = np.array([34,12,37,5,13])
heights = np.array([1.76,1.2,1.68,0.5,1.25])

#Sorting the #'s in the following line of code 
sort_indices = np.argsort(ages) 
print(persons[sort_indices]) # ['Will' 'Mary' 'Joe' 'Johnny' 'Peter'] 
print(ages[sort_indices]) # [ 5 12 13 34 37]
print(heights[sort_indices]) # [ 0.5 1.2 1.25 1.76 1.68]



['Will' 'Mary' 'Joe' 'Johnny' 'Peter']
[ 5 12 13 34 37]
[0.5  1.2  1.25 1.76 1.68]


Suppose that you want to sort this group of people by age.
 If you simply sort the ages array by itself, the other two arrays would not be sorted correctly based on age. This is where argsort() comes in really handy


### Sorting Ages
sort_indices = np.argsort(ages) # performs a sort based on ages # and returns an array of indices # indicating the sort order Once the sort indices are obtained, simply feed them into the three arrays: 


In [48]:
#Sorting the #'s in the following line of code 
sort_indices = np.argsort(ages) 
print(persons[sort_indices]) # ['Will' 'Mary' 'Joe' 'Johnny' 'Peter'] 
print(ages[sort_indices]) # [ 5 12 13 34 37]
print(heights[sort_indices]) # [ 0.5 1.2 1.25 1.76 1.68]

['Will' 'Mary' 'Joe' 'Johnny' 'Peter']
[ 5 12 13 34 37]
[0.5  1.2  1.25 1.76 1.68]


They would now be sorted based on age. As you can see, Will is the youngest, followed by Mary, and so on. The corresponding height for each person would also be in the correct order. 


### Sort By Name 
If you wish to sort based on name, then simply use argsort() on the persons array and feed the resulting indices into the three arrays: 


In [49]:
sort_indices = np.argsort(persons) # sort based on names
print(persons[sort_indices]) # ['Joe' 'Johnny' 'Mary' 'Peter' 'Will']
print(ages[sort_indices]) # [13 34 12 37 5]
print(heights[sort_indices]) # [ 1.25 1.76 1.2 1.68 0.5 ]


['Joe' 'Johnny' 'Mary' 'Peter' 'Will']
[13 34 12 37  5]
[1.25 1.76 1.2  1.68 0.5 ]
